const actionType = {
    //SignIn Actions
    USER_INIT_INFO: "USER_INIT_INFO",
    USER_SIGNIN_SUCCESS: "USER_SIGNIN_SUCCESS",
    USER_SIGNIN_FAIL: "USER_SIGNIN_FAIL",
    USER_LOGOUT: "USER_LOGOUT",
// USER_UPDATE_RESERVED: "USER_UPDATE_RESERVED",

    //Item Actions
    ITEM_LIST_REQUEST: "ITEM_LIST_REQUEST",
    ITEM_LIST_SUCCESS: "ITEM_LIST_SUCCESS",
    ITEM_LIST_FAIL: "ITEM_LIST_FAIL",
    ITEM_DETAILS_UPDATE_REQUEST: "ITEM_DETAILS_UPDATE_REQUEST",
    ITEM_DETAILS_UPDATE_SUCCESS: "ITEM_DETAILS_UPDATE_SUCCESS",
    ITEM_DETAILS_UPDATE_FAIL: "ITEM_DETAILS_UPDATE_FAIL",

    //Reserved Actions
    RESERVED_ITEMS_REQUEST:"RESERVED_ITEMS_REQUEST",
    RESERVED_GET_ITEMS:"RESERVED_GET_ITEMS",
    RESERVED_ITEMS_FAIL:"RESERVED_ITEMS_FAIL",
// RESERVED_ADD_ITEM:"RESERVED_ADD_ITEM",

// BORROW_ADD_ITEM : "BORROW_ADD_ITEM",
    BORROW_REMOVE_ITEM: "BORROW_REMOVE_ITEM",
};

export const SERVER_URL = "https://borrow-backend.herokuapp.com";
export default actionType;
